### ISSUE TITLE
python not found in $PATH

### ISSUE THREAD

**Issue by nakomoto** [glillico/docker-oraclelinux8-ansible#1]
Hi!

Thank you your great image. I have a suggestion for improvement:
Please symlink python to python3.

Thanks in advance,
nakomoto

**Comment by glillico** [comment]
Hi @nakomoto,

It is good to know that you are finding this useful.

I'm assuming that this has not been done in the base OS as you can have multiple versions of Python installed, and therefore this could result in unforeseen issues if symlinking in this way.

Regards
Graham
